# Generated by Django 5.1.6 on 2025-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_faculty_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
