# Generated by Django 5.1.6 on 2025-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_department_email_department_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
