# Generated by Django 5.1.6 on 2025-04-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_timetable_time_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
    ]
