# Generated by Django 5.1.6 on 2025-04-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_timetable_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
