# Generated by Django 5.1.7 on 2025-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timetable_day_of_week_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
